name: wg-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.23.1
  - scipy=1.8.1
  - pandas=1.4.3
  - matplotlib=3.5.2
  - statsmodels=0.13.2
  - xarray=2022.9.0
  - h5py=3.6.0
  - scikit-learn=1.0.2
  - joblib=1.2.0
  - cython=0.29.28
  - rasterio=1.2.10
  - pmdarima
  - pip
  - pip:
    - pomegranate==0.14.9
    - g2s
    - requests
